### ISSUE TITLE
Open login in default browser

### ISSUE THREAD

**Issue by raphaeltm** [expo/orbit#106]
### Is your feature request related to a problem? Please describe.

Right now if I click "Login" in the settings UI, it opens Safari.

Safari is not my default browser. Login should use my default browser.

### Describe the solution you'd like

Open the default browser instead of Safari.

### Additional context

The current behaviour is annoying because I never login with Safari. The app should launch the default browser since that's the most likely for the user to be already logged in.

**Comment by gabrieldonadel** [comment]
Hi @raphaeltm, I did some investigation on this and according to Apple's documentation, the system opens the user’s default browser if it supports web authentication sessions, or Safari otherwise. So most likely your default browser does not support web auth. I verified this with Google Chrome and it works as expected
