### ISSUE TITLE
Bypas Expo Orbit 

### ISSUE THREAD

**Issue by ogrunebaumrbi** [expo/orbit#207]
Been stuck on this for a week now.

<img width="256" alt="Screenshot 2024-10-15 at 3 30 57 PM" src="https://github.com/user-attachments/assets/619fd469-40ed-435f-89db-cd2243c05ab8">

Is there an easy way to entirely disable TLS verification in the application (when possible) or to configure the application to reference a certificate chain that has the Netskope certificate included. I can't remove the Netskope security from the machine.

I tried NODE_TLS_REJECT_UNAUTHORIZED but it didn't work. So was hoping to get your advice.

**Comment by wodin** [comment]
It sounds like you might need to add Netskope's CA cert to Expo Orbit's trusted root certificates. But I don't know if that's possible, or if so, how.

If it was using `node`, you might be able to set this option:
https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file

But it looks like it uses Hermes instead of node.

**Comment by gabrieldonadel** [comment]
Hi @ogrunebaumrbi, thanks for the report, do you know it there is a simple way to recreate this scenario (self-signed certificate in chain) in a local machine? I believe I have fix for this in #208 but I would like to confirm it before releasing a new version

**Comment by wodin** [comment]
@gabrieldonadel I think you'd need something that basically acts as a man-in-the-middle to intercept the connection and generate a certificate on the fly.
Or since you're not trying to actually intercept anyone's traffic, I would try this:
* Generate a self-signed certificate with the appropriate CN and/or SANs and install it on any web server.
* Then edit your `/etc/hosts` file to point the relevant names to this web server's IP address.
